

/* FUCNTION.H */



/* Gtalk */
/* Copyright (C) 1993, by David W Jeske, and Daniel L Marks */
/* Copying or distributing this source code without written  */
/* permission of David W Jeske and Daniel L Marks is strictly forbidden */



void repeat_chr(char chr,int times,char print_a_cr);  /* repeat a character
                                                         several times */
int nodes_free(void);
