


/* Gtalk */
/* Copyright (C) 1993, by David W Jeske, and Daniel L Marks */
/* Copying or distributing this source code without written  */
/* permission of David W Jeske and Daniel L Marks is strictly forbidden */



/* gtalk.h */
/* includes all gtalk standard includes */

#include "task.h"
#include "init.h"
#include "alloc.h"
#include "com.h"
#include "video.h"
#include "channel.h"
#include "io.h"
#include "gt.h"
#include "user.h"
#include "command.h"
#include "link.h"
#include "glink.h"
#include "structs.h"
#include "string.h"

#include "privs.h"
#include "toggles.h"

#include "input.h"
#include "editor.h"
#include "mail.h"
#include "rotator.h"
#include "gfiles.h"

#include "schedule.h"
#include "sysop.h"
#include "bbs.h"
#include "diags.h"
#include "protocol.h"

#include "define.h"
#include "function.h"

