


/* Gtalk */
/* Copyright (C) 1993, by David W Jeske, and Daniel L Marks */
/* Copying or distributing this source code without written  */
/* permission of David W Jeske and Daniel L Marks is strictly forbidden */



/*   Structs.h */





/**************
 *** video.c **
 **************/
 
 /* NO EXTERNS FROM VIDEO.C */
 
 

/*******************
 ***  COMMAND.C  ***
 *******************/
 
 /* no extern declarations at this point */
 
  
