



/* Gtalk */
/* Copyright (C) 1993, by David W Jeske, and Daniel L Marks */
/* Copying or distributing this source code without written  */
/* permission of David W Jeske and Daniel L Marks is strictly forbidden */


/* Toggles.h */


#define STREAM_TOG 1
#define ANSIOFF_TOG 2
#define SYSMON_TOG 3
#define LURKING_TOG 4
#define LINECOLORS_TOG 5
#define HARDANSION_TOG 6
#define ALLOWPAGE_TOG 7
#define DOUBLESPACE_TOG 8
#define NO_RETURN_ECHO_TOG 9


